name: Build and push Docker image

on:
  push:
    branches: [ master ]

env:
  JAVA_VERSION: 17
  GRAALVM_VERSION: 22.3.2
  DOCKER_IMAGE_NAME: altmerian/mn-graalvm-demo-app
  NATIVE_IMAGE_NAME: graalvm-demo-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version:  ${{ env.GRAALVM_VERSION }}
          java-version: ${{ env.JAVA_VERSION }}
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Running Tests
        run: ./gradlew test

      - name: Create native image
        run: ./gradlew nativeCompile

      - name: Create Docker image
        run: docker build --build-arg NATIVE_IMAGE_NAME=$NATIVE_IMAGE_NAME -t $DOCKER_IMAGE_NAME:latest .

      - name: Push Docker image
        run: docker push $DOCKER_IMAGE_NAME:latest
